DROP TABLE IF EXISTS TEST_PROCESS;
-- Creacion de tabla de prueba en h2
CREATE TABLE TEST_PROCESS(
   ID INT  PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(255),
   LAST_NAME VARCHAR(255),
   PROCESSED BOOLEAN);
-- insercion dde primer registro
  INSERT INTO TEST_PROCESS VALUES(NULL,'ALEXIS','HOLGUIN',FALSE);